# Generated by Django 2.2.1 on 2019-12-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaldatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('score', models.FloatField()),
                ('level', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('achived', models.IntegerField()),
                ('gender', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
